export const EMOJI_LIST = [
  { emoji: "🎯", keywords: "target goal project" },
  { emoji: "🚀", keywords: "rocket launch startup" },
  { emoji: "💡", keywords: "idea bulb light" },
  { emoji: "📌", keywords: "pin note" },
  { emoji: "📎", keywords: "clip attach" },
  { emoji: "📝", keywords: "note memo write" },
  { emoji: "📄", keywords: "document page file" },
  { emoji: "📁", keywords: "folder" },
  { emoji: "🗂️", keywords: "folder organize" },
  { emoji: "🗓️", keywords: "calendar date" },
  { emoji: "📅", keywords: "calendar date" },
  { emoji: "⏰", keywords: "alarm time clock" },
  { emoji: "⏳", keywords: "hourglass time" },
  { emoji: "✅", keywords: "check done complete" },
  { emoji: "☑️", keywords: "check box" },
  { emoji: "🔥", keywords: "fire hot urgent" },
  { emoji: "⭐", keywords: "star favorite" },
  { emoji: "🌟", keywords: "star sparkle" },
  { emoji: "🏆", keywords: "trophy win award" },
  { emoji: "🎉", keywords: "party celebrate" },
  { emoji: "🎨", keywords: "art design paint" },
  { emoji: "🖌️", keywords: "brush paint design" },
  { emoji: "🖥️", keywords: "computer desktop" },
  { emoji: "💻", keywords: "laptop computer code" },
  { emoji: "⌨️", keywords: "keyboard type" },
  { emoji: "🖱️", keywords: "mouse click" },
  { emoji: "📱", keywords: "phone mobile" },
  { emoji: "🛠️", keywords: "tools build fix" },
  { emoji: "🔧", keywords: "wrench tool fix" },
  { emoji: "⚙️", keywords: "gear settings" },
  { emoji: "🧩", keywords: "puzzle piece" },
  { emoji: "📊", keywords: "chart graph data" },
  { emoji: "📈", keywords: "chart growth" },
  { emoji: "📉", keywords: "chart decline" },
  { emoji: "💰", keywords: "money finance" },
  { emoji: "💳", keywords: "card payment" },
  { emoji: "🏦", keywords: "bank finance" },
  { emoji: "🧾", keywords: "receipt invoice" },
  { emoji: "🛒", keywords: "cart shopping ecommerce" },
  { emoji: "📦", keywords: "box package" },
  { emoji: "🚚", keywords: "truck delivery" },
  { emoji: "✈️", keywords: "plane travel" },
  { emoji: "🌍", keywords: "world globe" },
  { emoji: "🗺️", keywords: "map" },
  { emoji: "🏠", keywords: "home house" },
  { emoji: "🏢", keywords: "office building" },
  { emoji: "🏗️", keywords: "construction build" },
  { emoji: "🧱", keywords: "brick build" },
  { emoji: "🔒", keywords: "lock secure" },
  { emoji: "🔑", keywords: "key access" },
  { emoji: "🛡️", keywords: "shield security" },
  { emoji: "🔍", keywords: "search find" },
  { emoji: "🔬", keywords: "science research" },
  { emoji: "🧪", keywords: "test experiment" },
  { emoji: "📚", keywords: "books read docs" },
  { emoji: "📖", keywords: "book read" },
  { emoji: "✏️", keywords: "pencil write edit" },
  { emoji: "🖊️", keywords: "pen write" },
  { emoji: "🎓", keywords: "graduate education" },
  { emoji: "🧠", keywords: "brain think idea" },
  { emoji: "💬", keywords: "chat comment message" },
  { emoji: "📣", keywords: "announce marketing" },
  { emoji: "📢", keywords: "announce loud" },
  { emoji: "📧", keywords: "email mail" },
  { emoji: "✉️", keywords: "envelope mail" },
  { emoji: "🔔", keywords: "bell notification" },
  { emoji: "🎵", keywords: "music note" },
  { emoji: "🎬", keywords: "movie video film" },
  { emoji: "📷", keywords: "camera photo" },
  { emoji: "🖼️", keywords: "picture image frame" },
  { emoji: "🎮", keywords: "game controller" },
  { emoji: "🕹️", keywords: "game joystick" },
  { emoji: "⚽", keywords: "sport ball" },
  { emoji: "🏀", keywords: "sport basketball" },
  { emoji: "🧗", keywords: "climb goal" },
  { emoji: "🏃", keywords: "run sprint" },
  { emoji: "🌱", keywords: "plant grow" },
  { emoji: "🌳", keywords: "tree nature" },
  { emoji: "🌈", keywords: "rainbow color" },
  { emoji: "☀️", keywords: "sun weather" },
  { emoji: "🌙", keywords: "moon night" },
  { emoji: "⚡", keywords: "lightning fast energy" },
  { emoji: "❄️", keywords: "snow cold" },
  { emoji: "🍀", keywords: "clover luck" },
  { emoji: "🐝", keywords: "bee busy" },
  { emoji: "🦄", keywords: "unicorn magic" },
  { emoji: "🤖", keywords: "robot ai automation" },
  { emoji: "👥", keywords: "people team" },
  { emoji: "🧑‍💻", keywords: "developer coder" },
  { emoji: "🧑‍🎨", keywords: "designer artist" },
  { emoji: "🧑‍🚀", keywords: "astronaut space" },
  { emoji: "🤝", keywords: "handshake deal partner" },
  { emoji: "👍", keywords: "thumbs up approve" },
  { emoji: "❤️", keywords: "heart love" },
  { emoji: "🧡", keywords: "heart orange" },
  { emoji: "💚", keywords: "heart green" },
  { emoji: "💙", keywords: "heart blue" },
  { emoji: "💜", keywords: "heart purple" },
];
